[functions.stripe-webhook]
verify_jwt = false

[functions.create-checkout-session]
verify_jwt = false

[functions.login-with-password]
verify_jwt = false

[functions.get-client-bookings]
verify_jwt = false

[functions.get-client-podcasts]
verify_jwt = false

[functions.get-prospect-podcasts]
verify_jwt = false

[functions.create-client-account]
enabled = true
verify_jwt = true
import_map = "./functions/create-client-account/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/create-client-account/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/create-client-account/*.html" ]

[functions.generate-client-bio]
enabled = true
verify_jwt = true
import_map = "./functions/generate-client-bio/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/generate-client-bio/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/generate-client-bio/*.html" ]

[functions.create-outreach-message]
verify_jwt = false

[functions.fetch-podscan-email]
verify_jwt = false

[functions.create-bison-lead]
verify_jwt = false

[functions.generate-tagline]
verify_jwt = false
